name: Build and deploy static web app to Azure Web App - chakkour-khadija

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip static files for deployment
        run: zip -r release.zip ./Portfolio # Zipper tous les fichiers du dossier Portfolio

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-web-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-web-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A5F361F72BE7416BAE676ED857BD8C22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1EA34B1FCF174F0DAFF394A4A0257D11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_616F6C3C5B5E4192B6B1CC6F97F6AA4B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chakkour-khadija'
          slot-name: 'Production'
          package: ./app # Utilisez le répertoire décompressé où les fichiers sont stockés
